- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.axelrc:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.emacs.d:
    ~/.emacs:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    ~/.hgrc:
    ~/.inputrc:
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.irssi:
    ~/.jupyter/jupyter_notebook_config.py: jupyter/jupyter_notebook_config.py
    ~/.jupyter/nbconfig/notebook.json: jupyter/notebook.json
    ~/.local/share/jupyter/nbextensions: jupyter/nbextensions
    ~/.pythonrc:
    ~/.rtorrent.rc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    emacs.d/vendor/
    irssi/scripts/vendor/
    jupyter/nbextensions/
    shell/plugins/
    vim/bundle/
    zsh/plugins/
