- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.axelrc:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gdbinit:
    ~/.gitconfig:
    ~/.cgdb:
    ~/.gitignore_global:
    ~/.haskeline:
    ~/.hgrc:
    ~/.inputrc:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.pythonrc:
    ~/.rtorrent.rc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.vimrc_local:
    ~/.ideavimrc:
    ~/.vsvimrc:
    ~/.zsh:
    ~/.zshrc:
    # ~/.zfunctions/prompt_spaceship_setup: zsh/prompt/spaceship-prompt/spaceship.zsh

- create:
  - ~/.rtorrent/session
  - ~/.rtorrent/watch
  - ~/.rtorrent/downloads

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
