require "user.conf.nvim-tree"
require "user.conf.cmp"
require "user.conf.telescope"
require "user.conf.treesitter"
require "user.conf.autopairs"
require "user.conf.comment"
require "user.conf.gitsigns"
require "user.conf.bufferline"
require "user.conf.onedark"
require "user.conf.lualine"
require "user.conf.toggleterm"
require "user.conf.project"
require "user.conf.impatient"
require "user.conf.indent-blankline"
require "user.conf.alpha"
require "user.conf.whichkey"
require "user.conf.autocommands"
-- require "user.conf.nvim-hlslens"
require "user.conf.hop"
require "user.conf.vim-illuminate"
require "user.conf.nvim-lastplace"
require "user.conf.auto-session"
require "user.conf.todo-comments"
-- require "user.conf.vista"
-- require "user.conf.symbols-outline"
require "user.conf.treesitter-context"
require "user.conf.nvim-gps"
require "user.conf.vim-match"
require "user.conf.nvim-colorizer"
-- require "user.conf.tabout"
require "user.conf.trouble"
require "user.conf.filetype"
require "user.conf.aerial"
require "user.conf.nvim-lightbulb"
require "user.conf.nvim-spectre"
require "user.conf.vim-cmake"
require "user.conf.winshift"
require "user.conf.high-str"
require "user.conf.nvim-startup" -- startup time calc
-- require "user.conf.startup"  -- welcome page
